name: Actualizacion README.md de Perfil ( Node.js CI )

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: npm install
    - run: npm run update-readme
    - run: |
        git config user.name moonantonio
        git config user.email pinchodev91@gmail.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Autogeneracion del README"
        git push origin master
