# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm install
    - run: npm run update-readme
    
    - run: |
        git config user.name MoonAntonio
        git config user.email antoniomt.moon@gmail.com
        git add README.md
        git commit -m "[bot] Autogeneracion del README"
        git push origin master

